server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: civic-alert
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:55432}/${DB_NAME:civicalert}
    username: ${DB_USER:civicalert_user}
    password: ${DB_PASSWORD:civicalert_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: false

logging:
  level:
    org.hibernate.SQL: WARN
